import { expect, test, type Page } from '@playwright/test'

async function choose(page: Page, name: string, option: string) {
  await page.getByRole('combobox', { name, exact: true }).click()
  await page.getByRole('option', { name: option, exact: true }).click()
}
async function createClass(page: Page, title: string) {
  await page.goto('/')
  await page.getByRole('button', { name: '新建课堂', exact: true }).click()
  await choose(page, '所属课程', '＋ 创建新课程')
  await page.getByRole('textbox', { name: '新课程名称' }).fill(title + '课程')
  await page.getByRole('textbox', { name: '课堂名称（选填）' }).fill(title)
  await page.getByRole('button', { name: '创建课堂', exact: true }).click()
  await expect(page).toHaveURL(/lessons\//)
}
async function configure(page: Page) {
  await page.goto('/settings')
  await choose(page, '工作空间区域', 'cn-beijing')
  await page
    .getByRole('textbox', { name: '工作空间兼容地址' })
    .fill('https://dashscope.aliyuncs.com/compatible-mode/v1')
  await page.getByRole('button', { name: '保存设置', exact: true }).click()
  await page.getByRole('textbox', { name: 'API Key', exact: true }).fill('test-key-for-fake-provider')
  await page.getByRole('button', { name: '单独保存 Key', exact: true }).click()
  await expect(page.getByText('Key 已保存，尚未调用模型')).toBeVisible()
}
test('empty startup, class creation, refresh, themes, English and narrow keyboard flow', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (e) => errors.push(e.message))
  await createClass(page, '浏览器验收')
  await expect(page.getByRole('heading', { name: '课堂转写', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: '课堂问答', exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: '聊天消息' }).fill('尚未发送的草稿')
  await page.reload()
  await expect(page.getByRole('textbox', { name: '聊天消息' })).toHaveValue('尚未发送的草稿')
  await page.screenshot({ path: 'test-results/workspace-desktop.png', fullPage: true })
  await page.getByRole('button', { name: '深色', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.getByRole('button', { name: '跟随系统', exact: true }).click()
  await page.setViewportSize({ width: 560, height: 820 })
  await page.getByRole('button', { name: '聊天', exact: true }).click()
  await expect(page.getByRole('textbox', { name: '聊天消息' })).toBeVisible()
  await page.screenshot({ path: 'test-results/workspace-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('button', { name: '中文 / EN' }).click()
  await expect(page.getByRole('heading', { name: 'Transcript', exact: true })).toBeVisible()
  expect(errors).toEqual([])
})
test('saved settings, record stop, post-class chat, summary, export and source playback', async ({
  page,
}) => {
  await configure(page)
  await createClass(page, '完整流程')
  await page.getByRole('button', { name: '开始录音', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '开始一次新录音' })
  await dialog.getByRole('button', { name: '开始录音', exact: true }).click()
  await expect(page.locator('.record-status').getByText('录音中', { exact: true })).toBeVisible()
  await page.waitForTimeout(500)
  await page.locator('.work-actions').getByRole('button', { name: '停止采集' }).click()
  await expect(page.getByText('这是课堂内容：为什么矩阵乘法不满足交换律？').first()).toBeVisible({
    timeout: 15000,
  })
  await expect(page.locator('.question-card').first()).toBeVisible({ timeout: 15000 })
  await page.getByRole('textbox', { name: '聊天消息' }).fill('为什么不满足交换律？')
  await page.getByRole('textbox', { name: '聊天消息' }).press('Enter')
  await expect(page.locator('.assistant-message .markdown')).toContainText('矩阵表示线性映射', {
    timeout: 15000,
  })
  await page.getByRole('button', { name: '课堂总结', exact: true }).click()
  await page.getByRole('button', { name: '生成新的总结' }).click()
  await expect(page.locator('.summary-card .badge')).toHaveText('已完成', { timeout: 15000 })
  await page.getByRole('button', { name: '关闭面板' }).click()
  const downloadPromise = page.waitForEvent('download')
  await page.getByTitle('导出完整 Markdown').click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toMatch(/\.md$/)
  await page.getByRole('button', { name: '音频来源', exact: true }).click()
  await expect(page.locator('.player').getByRole('button', { name: '播放', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: '下载 MP3' })).toBeVisible()
  await page.getByRole('button', { name: '关闭面板' }).click()
  await page.screenshot({ path: 'test-results/workspace-populated.png', fullPage: true })
})
test('unsaved settings can stay on page or discard on navigation', async ({ page }) => {
  await page.goto('/settings')
  await choose(page, '生成语言', 'English')
  await page.getByRole('link', { name: '我的课堂', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '有未保存的更改' })).toBeVisible()
  await page.getByRole('button', { name: '继续编辑' }).click()
  await expect(page).toHaveURL(/settings$/)
  await page.getByRole('link', { name: '我的课堂', exact: true }).click()
  await page.getByRole('button', { name: '放弃并离开' }).click()
  await expect(page).toHaveURL('http://127.0.0.1:29039/')
})

test('upload, confirm analysis, refresh, and synchronize another tab', async ({ page, context }) => {
  await createClass(page, '导入与同步')
  const second = await context.newPage()
  await second.goto(page.url())
  await page.getByRole('button', { name: '音频来源', exact: true }).click()
  const samples = 8000
  const wav = Buffer.alloc(44 + samples * 2)
  wav.write('RIFF', 0)
  wav.writeUInt32LE(36 + samples * 2, 4)
  wav.write('WAVE', 8)
  wav.write('fmt ', 12)
  wav.writeUInt32LE(16, 16)
  wav.writeUInt16LE(1, 20)
  wav.writeUInt16LE(1, 22)
  wav.writeUInt32LE(16000, 24)
  wav.writeUInt32LE(32000, 28)
  wav.writeUInt16LE(2, 32)
  wav.writeUInt16LE(16, 34)
  wav.write('data', 36)
  wav.writeUInt32LE(samples * 2, 40)
  for (let i = 0; i < samples; i++) wav.writeInt16LE(2000, 44 + i * 2)
  await page
    .locator('input[type=file]')
    .setInputFiles({ name: 'browser-audio.wav', mimeType: 'audio/wav', buffer: wav })
  const dialog = page.getByRole('dialog', { name: '分析这份录音' })
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: '开始分析', exact: true }).click()
  await page.getByRole('button', { name: '关闭面板' }).click()
  await expect(second.locator('.transcript-row')).toHaveCount(1, { timeout: 15000 })
  await second.reload()
  await expect(second.locator('.transcript-row')).toHaveCount(1)
  await second.getByRole('textbox', { name: '聊天消息' }).fill('从另一标签页发送')
  await second.getByRole('textbox', { name: '聊天消息' }).press('Enter')
  await expect(page.locator('.user-message')).toContainText('从另一标签页发送')
  await expect(page.locator('.assistant-message .markdown')).toContainText('矩阵表示线性映射')
  await second.close()
})
